# Reis标识下的数据
[redis]
# Redis 服务器地址列表
# 对于单机版，只需一个地址；对于主从或集群模式，可以提供多个地址
addrs = ["${REDIS_HOST:redis_demo}:${REDIS_PORT:6379}"]

# Redis 服务器密码
# 如果没有密码，可以留空
password = ""

# 使用的数据库索引
# Redis 默认有 16 个数据库（0-15），通常使用 0
db = 0

# 连接池大小
# 控制客户端可以打开的最大连接数
pool_size = 10

# 最小空闲连接数
# 保持的最小空闲连接数
min_idle_conns = 2

# 连接超时时间（秒）
dial_timeout = 5

# 读操作超时时间（秒）
read_timeout = 3

# 写操作超时时间（秒）
write_timeout = 3

# 最大重试次数
# 在操作失败时，客户端重试的最大次数
max_retries = 3
