http:
  address: "${SERVER_ADDRESS:0.0.0.0}"
  port: ${SERVER_PORT:8080}
  shutdown_timeout: 5
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120
  authorization: "Bearer ${AUTHORIZATION:123456}" # 授权码